#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source "$PROJECT_ROOT/scripts/env/common.sh"

echo "PROJECT_ROOT=$PROJECT_ROOT"
echo "NIX_ISOLATED_ROOT=$NIX_ISOLATED_ROOT"
echo "NIX_CONF_DIR=$NIX_CONF_DIR"
echo "HOME=$HOME"
echo "XDG_CONFIG_HOME=$XDG_CONFIG_HOME"
echo "XDG_CACHE_HOME=$XDG_CACHE_HOME"
echo "XDG_DATA_HOME=$XDG_DATA_HOME"
echo "XDG_STATE_HOME=$XDG_STATE_HOME"
echo "PYTHON_DIR=$PYTHON_DIR"
echo "VIRTUAL_ENV=$VIRTUAL_ENV"
echo "PIP_CACHE_DIR=$PIP_CACHE_DIR"
echo "POETRY_CACHE_DIR=$POETRY_CACHE_DIR"
echo "UV_CACHE_DIR=$UV_CACHE_DIR"
echo "PYTHONPYCACHEPREFIX=$PYTHONPYCACHEPREFIX"
echo "SWIFT_BUILD_PATH=$SWIFT_BUILD_PATH"
echo "CACTUS_MODEL_PATH=$CACTUS_MODEL_PATH"
echo "LITERT_LM_MODELS=$LITERT_LM_MODELS"
