version = 1

[include]
environments = [
	{ dir = "../base" },
	{ dir = "../python" },
	{ dir = "../swift" },
	{ dir = "../inference" },
]

[hook]
on-activate = '''
source scripts/env/toolchain/common.sh
export HYBRID_AI_PROFILE=${HYBRID_AI_PROFILE:-fullstack}
'''
