version = 1

[install]
curl.pkg-path = "curl"
jq.pkg-path = "jq"
git.pkg-path = "git"

[include]
environments = [
	{ dir = "../base" },
]

[hook]
on-activate = '''
source scripts/env/toolchain/inference_env.sh
'''
