version = 1

[install]
python.pkg-path = "python311"
python.systems = ["x86_64-linux"]
poetry.pkg-path = "poetry"
poetry.systems = ["x86_64-linux"]
uv.pkg-path = "uv"
uv.systems = ["x86_64-linux"]
libgcc.pkg-path = "libgcc"
libgcc.systems = ["x86_64-linux"]

[include]
environments = [
	{ dir = "../base" },
]

[hook]
on-activate = '''
source scripts/env/toolchain/python/python_env.sh
hybrid_ai_setup_python_env
'''

[profile]
common = '''
source scripts/env/toolchain/python/python_env.sh
hybrid_ai_activate_python_env
'''
