version = 1

[install]
cmake.pkg-path = "cmake"
gtk4.pkg-path = "gtk4"
libadwaita.pkg-path = "libadwaita"
pkg-config.pkg-path = "pkg-config"
gobject-introspection.pkg-path = "gobject-introspection"
libsysprof-capture.pkg-path = "libsysprof-capture"
pcre2.pkg-path = "pcre2"
libselinux.pkg-path = "libselinux"
libselinux.systems = ["x86_64-linux", "aarch64-linux"]
libsepol.pkg-path = "libsepol"
libsepol.systems = ["x86_64-linux", "aarch64-linux"]
fribidi.pkg-path = "fribidi"
libthai.pkg-path = "libthai"
libdatrie.pkg-path = "libdatrie"
expat.pkg-path = "expat"
libXdmcp.pkg-path = "xorg.libXdmcp"
libdeflate.pkg-path = "libdeflate"
lerc.pkg-path = "lerc"
xz.pkg-path = "xz"

[include]
environments = [
	{ dir = "../base" },
]

[vars]
SWIFTLY_ROOT = "/opt/bin/dev/swiftly"
SWIFTLY_HOME_DIR = "/opt/bin/dev/swiftly/home"
SWIFTLY_BIN_DIR = "/opt/bin/dev/swiftly/bin"
SWIFTLY_TOOLCHAINS_DIR = "/opt/bin/dev/swiftly/toolchains"
SWIFTLY_VERSION = "1.1.1"
HYBRID_AI_SWIFT_VERSION = "6.3.2"
GTK_A11Y = "none"

[hook]
on-activate = '''
source scripts/env/toolchain/swift/swift_env.sh
hybrid_ai_activate_swift_env
'''

[profile]
common = '''
source scripts/env/toolchain/swift/swift_env.sh
hybrid_ai_activate_swift_env
'''
